### ISSUE TITLE
 Installation problems

### ISSUE THREAD

**Issue by erdanieee** [giano/Telegrammer#1]
telegrammer@0.5.4 start Telegrammer

> $./tel.sh start

/home/dlopez/software/Telegrammer/node_modules/lodash/lodash.js:9763
        throw new TypeError(FUNC_ERROR_TEXT);
        ^

TypeError: Expected a function
    at Function.rest (/home/dlopez/software/Telegrammer/node_modules/lodash/lodash.js:9763:15)
    at /home/dlopez/software/Telegrammer/bin/telegrammer.js:5:18
    at Object.<anonymous> (/home/dlopez/software/Telegrammer/bin/telegrammer.js:22:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

> $nodejs -v

v5.10.1

> $npm -v

3.8.3

**Comment by giano** [comment]
Thank you for the submission. I'll test on Node 5.10 ASAP. Currently running on LTS 4 branch.

**Comment by giano** [comment]
Ok, pinpointed. Lodash doesn't have a "rest" function, while Underscore has it. Rewriting as a simple splice. Will push tomorrow.

**Comment by giano** [comment]
Published a fast fix. Will start but new hooks and config directory start options are untested. Thank you erdanieee

**Comment by erdanieee** [comment]
Thank you very much for your very fast fix! I'll try to install it again...

**Comment by giano** [comment]
Ok. Keep in mind that I'll update npm version this weekend when I'm sure new config options works. Thank you for your bug reporting.

**Comment by erdanieee** [comment]
Hi again, after the update I could install it correctly:

> $./tel.sh start

```
telegrammer v0.5.5 starting...

Using bot @svvpaBot, svvpa, ID: 202XXXXXX

Hooked to chat id #XXXXXXXXX
```

The problem is that it seems it can't receive any command from Telegram. I try to send commands like /start, /stop, /help /beep, /helloworld /mawkish and I don't get any response in the chat. I've also try to register manually those commmands in @BotFather, but still doesn't work. However, the spammer example works fine:

> $./tel.sh examples:spammer -w "test"

Here is my config/shared.json:

```
{
        "telegram": {
                "token": "197769581:AAFPxgXu8k7aae2XXXXXXXXXXXXXXXXXXX",
                "chat_id": "202XXXXXX",
                "parse_mode": "Markdown"
        },
        "hooks": {
                "folder": "hooks",
                "config": {
                        "monitor_cpu": {
                                "percent_limit": 70
                        }
                }
        },
        "commandline": {
                "active": true
        },
        "monitor": {
                "active": false,
                "default_interval": 5000
        },
        "local": {
                "active": true
        },
        "express": {
                "active": false,
                "auth": "EXTRA-SECURITY-FOR-WEB-HOOKS",
                "auth_token_name": "X-Auth"
        },      
        "verbose":true
}
```

**Comment by giano** [comment]
Sorry, not all of the commands you are issuing are registered as "commands". You can navigate to your Telegrammer url, default port 3000 to have a list of commands. You can send /import_commands to have a list of commands you can directly import in @BotFather (no way to do it from code at the moment). 
Do you have any log in console?

**Comment by giano** [comment]
try to issue /love command. Do you have any response?

**Comment by erdanieee** [comment]
I can see those commands in Telegrammer url. I have no response from /love

**Comment by erdanieee** [comment]
How can I send  /import_commands from command line?

**Comment by erdanieee** [comment]
I didn't see any log in console...

**Comment by giano** [comment]
You can send /import_commands from Telegram. Your config seems ok, chat id too or the spammer would not work.  Did you left hooks/sys directory? I will patch the startup procedure to log registered commands, would be useful in those situations. Any firewall in between?

**Comment by erdanieee** [comment]
/import_dommands doesn't work. I only removed hooks interacting with gpio, because I'm working know with my laptop. The rest of the files are the original one

**Comment by erdanieee** [comment]
Probably the router is blocking some connection. Which port is supposed to be opened?

**Comment by giano** [comment]
Ok, thanks. 
Try to issue from command line ./tel stop. Then restart commenting out chat_id. Then send any command (/start for example, or /help). Do you get same chat id?
No problem with that kind of firewall. Only had issue with one with packet sniffing.

**Comment by erdanieee** [comment]
I can get get the chat_id this way. Actually, I've used a perl script to get the chat_id

```
#!/usr/bin/perl

use Data::Dumper;
use WWW::Telegram::BotAPI;

my $TOKEN = '197769581:AAFPxgXXXXXXXXXXXXXXXXXXXXXX';
my $api = WWW::Telegram::BotAPI->new (
    token => $TOKEN
) or die "I can't connect";

my $out = $api->api_request ('getUpdates');
warn Dumper($out);
my $chat_id = $out->{result}->[0]->{message}->{chat}->{id};
print "chat_id=$chat_id\n";
```

**Comment by giano** [comment]
Ok.  try adding allowed_usernames:["your_username_in_lowercase"] at config root. I think I pinpointed it.

**Comment by erdanieee** [comment]
username is name_surname, right? It doesn't work, but my surname is not the best test, because has special characters: 

> Daniel_López

**Comment by giano** [comment]
ok, pushing a patch now. Thank you for beta testing it, and sorry for misconfiguration.

**Comment by giano** [comment]
ok, patch pushed. You can enter your allowed username as this
`
allowed_usernames: ["daniel_lópez"] 
`
(all lowercase) or try to remove it. 
I think I fixed it.

**Comment by giano** [comment]
Published new version on NPM too. If you start with --verbose option (or just -V) it will log all registered hooks. If it's working for you feel free to close issue.

**Comment by erdanieee** [comment]
It works like a charm! Thank you for your fast reply. I think the problem was I tested it using the same telegram Id for sending msg and register the bot...
Just one question, I'd like to write custom hooks, would you recommend any IDE for Linux?

**Comment by giano** [comment]
I mostly use [Atom](https://atom.io) for node projects. Not the fastest ever used but has a lot of features for node (being written in node itself). Born on Mac but can run on some Linux distros too. Others you can try are Sublime Text and Brackets. Faster, but less specific. Many are for Vi and the like, but I never got used to them. Have a nice hack, and feel free to push your hooks If you want.
